nelmio_api_doc:
    documentation:
        info:
            title: Cart Service API
            description: Cart service OpenAPI specification.
            version: 1.0.0
        components:
            securitySchemes:
                XUserId:
                    type: apiKey
                    in: header
                    name: X-User-Id
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
