x-php-load-test-runtime: &php-load-test-runtime
  build:
    target: load-test
  image: symfony-runtime:load-test

services:
  symfony-cli:
    <<: *php-load-test-runtime

  symfony-web:
    <<: *php-load-test-runtime

  catalog-web:
    <<: *php-load-test-runtime

  catalog-cli:
    <<: *php-load-test-runtime

  catalog-grpc:
    <<: *php-load-test-runtime

  cart-web:
    <<: *php-load-test-runtime

  cart-cli:
    <<: *php-load-test-runtime
