<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260716100353 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE catalog_elements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sort INT DEFAULT 100 NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_769DD9434584665A ON catalog_elements (product_id)');

        //the desc direction is not generated automatically so always check it if modify this migration
        $this->addSql('CREATE INDEX idx_catalog_elements_sort_id ON catalog_elements (sort desc, id)');


        $this->addSql('CREATE TABLE catalog_sections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, description TEXT DEFAULT NULL, picture_id VARCHAR(255) DEFAULT NULL, level INT NOT NULL, left_margin INT NOT NULL, right_margin INT NOT NULL, sort INT DEFAULT 100 NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19419D86989D9B62 ON catalog_sections (slug)');
        $this->addSql('CREATE INDEX IDX_19419D86727ACA70 ON catalog_sections (parent_id)');
        $this->addSql('CREATE TABLE price_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, active BOOLEAN NOT NULL, sort INT DEFAULT 100 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F18CA59377153098 ON price_type (code)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, created_by INT NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, picture_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04AD989D9B62 ON product (slug)');
        $this->addSql('CREATE TABLE product_catalog_sections (product_id INT NOT NULL, catalog_section_id INT NOT NULL, PRIMARY KEY (product_id, catalog_section_id))');
        $this->addSql('CREATE INDEX IDX_97CDF97A4584665A ON product_catalog_sections (product_id)');
        $this->addSql('CREATE INDEX IDX_97CDF97A6D0911A1 ON product_catalog_sections (catalog_section_id)');
        $this->addSql('CREATE TABLE product_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, currency VARCHAR(3) NOT NULL, active BOOLEAN NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, price_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B9459854584665A ON product_price (product_id)');
        $this->addSql('CREATE INDEX IDX_6B945985AE6A44CF ON product_price (price_type_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_price_type ON product_price (product_id, price_type_id)');
        $this->addSql('CREATE TABLE product_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, original_product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E7FD7FA24584665A ON product_snapshot (product_id)');
        $this->addSql('CREATE INDEX IDX_E7FD7FA2283311CE ON product_snapshot (original_product_id)');
        $this->addSql('CREATE TABLE stores (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5907CCC989D9B62 ON stores (slug)');
        $this->addSql('CREATE TABLE stores_elements_stocks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stock INT NOT NULL, store_id INT NOT NULL, element_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C2B6652B092A811 ON stores_elements_stocks (store_id)');
        $this->addSql('CREATE INDEX IDX_4C2B66521F1F2A24 ON stores_elements_stocks (element_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_store_element_stock ON stores_elements_stocks (store_id, element_id)');
        $this->addSql('ALTER TABLE catalog_elements ADD CONSTRAINT FK_769DD9434584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE catalog_sections ADD CONSTRAINT FK_19419D86727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_sections (id)');
        $this->addSql('ALTER TABLE product_catalog_sections ADD CONSTRAINT FK_97CDF97A4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_catalog_sections ADD CONSTRAINT FK_97CDF97A6D0911A1 FOREIGN KEY (catalog_section_id) REFERENCES catalog_sections (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B9459854584665A FOREIGN KEY (product_id) REFERENCES catalog_elements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985AE6A44CF FOREIGN KEY (price_type_id) REFERENCES price_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_snapshot ADD CONSTRAINT FK_E7FD7FA24584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_snapshot ADD CONSTRAINT FK_E7FD7FA2283311CE FOREIGN KEY (original_product_id) REFERENCES catalog_elements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stores_elements_stocks ADD CONSTRAINT FK_4C2B6652B092A811 FOREIGN KEY (store_id) REFERENCES stores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stores_elements_stocks ADD CONSTRAINT FK_4C2B66521F1F2A24 FOREIGN KEY (element_id) REFERENCES catalog_elements (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE catalog_elements DROP CONSTRAINT FK_769DD9434584665A');
        $this->addSql('ALTER TABLE catalog_sections DROP CONSTRAINT FK_19419D86727ACA70');
        $this->addSql('ALTER TABLE product_catalog_sections DROP CONSTRAINT FK_97CDF97A4584665A');
        $this->addSql('ALTER TABLE product_catalog_sections DROP CONSTRAINT FK_97CDF97A6D0911A1');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B9459854584665A');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985AE6A44CF');
        $this->addSql('ALTER TABLE product_snapshot DROP CONSTRAINT FK_E7FD7FA24584665A');
        $this->addSql('ALTER TABLE product_snapshot DROP CONSTRAINT FK_E7FD7FA2283311CE');
        $this->addSql('ALTER TABLE stores_elements_stocks DROP CONSTRAINT FK_4C2B6652B092A811');
        $this->addSql('ALTER TABLE stores_elements_stocks DROP CONSTRAINT FK_4C2B66521F1F2A24');
        $this->addSql('DROP TABLE catalog_elements');
        $this->addSql('DROP TABLE catalog_sections');
        $this->addSql('DROP TABLE price_type');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_catalog_sections');
        $this->addSql('DROP TABLE product_price');
        $this->addSql('DROP TABLE product_snapshot');
        $this->addSql('DROP TABLE stores');
        $this->addSql('DROP TABLE stores_elements_stocks');
    }
}
