<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260705152707 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'catalog migration';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE catalog_elements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, created_by INT NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, picture_id VARCHAR(255) DEFAULT NULL, sort INT DEFAULT 100 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_769DD943989D9B62 ON catalog_elements (slug)');
        $this->addSql('CREATE TABLE catalog_elements_catalog_sections (catalog_elements_id INT NOT NULL, catalog_sections_id INT NOT NULL, PRIMARY KEY (catalog_elements_id, catalog_sections_id))');
        $this->addSql('CREATE INDEX IDX_13C51807CAD96770 ON catalog_elements_catalog_sections (catalog_elements_id)');
        $this->addSql('CREATE INDEX IDX_13C5180746CD274A ON catalog_elements_catalog_sections (catalog_sections_id)');
        $this->addSql('CREATE TABLE catalog_sections (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, description TEXT DEFAULT NULL, picture_id VARCHAR(255) DEFAULT NULL, level INT NOT NULL, left_margin INT NOT NULL, right_margin INT NOT NULL, sort INT DEFAULT 100 NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_19419D86989D9B62 ON catalog_sections (slug)');
        $this->addSql('CREATE INDEX IDX_19419D86727ACA70 ON catalog_sections (parent_id)');
        $this->addSql('CREATE TABLE price_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, active BOOLEAN NOT NULL, sort INT DEFAULT 100 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F18CA59377153098 ON price_type (code)');
        $this->addSql('CREATE TABLE product_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, currency VARCHAR(3) NOT NULL, active BOOLEAN NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, price_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B9459854584665A ON product_price (product_id)');
        $this->addSql('CREATE INDEX IDX_6B945985AE6A44CF ON product_price (price_type_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_price_type ON product_price (product_id, price_type_id)');
        $this->addSql('CREATE TABLE stores (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5907CCC989D9B62 ON stores (slug)');
        $this->addSql('CREATE TABLE stores_elements_stocks (stock INT NOT NULL, store_id INT NOT NULL, element_id INT NOT NULL, PRIMARY KEY (store_id, element_id))');
        $this->addSql('CREATE INDEX IDX_4C2B6652B092A811 ON stores_elements_stocks (store_id)');
        $this->addSql('CREATE INDEX IDX_4C2B66521F1F2A24 ON stores_elements_stocks (element_id)');
        $this->addSql('ALTER TABLE catalog_elements_catalog_sections ADD CONSTRAINT FK_13C51807CAD96770 FOREIGN KEY (catalog_elements_id) REFERENCES catalog_elements (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE catalog_elements_catalog_sections ADD CONSTRAINT FK_13C5180746CD274A FOREIGN KEY (catalog_sections_id) REFERENCES catalog_sections (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE catalog_sections ADD CONSTRAINT FK_19419D86727ACA70 FOREIGN KEY (parent_id) REFERENCES catalog_sections (id)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B9459854584665A FOREIGN KEY (product_id) REFERENCES catalog_elements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985AE6A44CF FOREIGN KEY (price_type_id) REFERENCES price_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stores_elements_stocks ADD CONSTRAINT FK_4C2B6652B092A811 FOREIGN KEY (store_id) REFERENCES stores (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stores_elements_stocks ADD CONSTRAINT FK_4C2B66521F1F2A24 FOREIGN KEY (element_id) REFERENCES catalog_elements (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE catalog_elements_catalog_sections DROP CONSTRAINT FK_13C51807CAD96770');
        $this->addSql('ALTER TABLE catalog_elements_catalog_sections DROP CONSTRAINT FK_13C5180746CD274A');
        $this->addSql('ALTER TABLE catalog_sections DROP CONSTRAINT FK_19419D86727ACA70');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B9459854584665A');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985AE6A44CF');
        $this->addSql('ALTER TABLE stores_elements_stocks DROP CONSTRAINT FK_4C2B6652B092A811');
        $this->addSql('ALTER TABLE stores_elements_stocks DROP CONSTRAINT FK_4C2B66521F1F2A24');
        $this->addSql('DROP TABLE catalog_elements');
        $this->addSql('DROP TABLE catalog_elements_catalog_sections');
        $this->addSql('DROP TABLE catalog_sections');
        $this->addSql('DROP TABLE price_type');
        $this->addSql('DROP TABLE product_price');
        $this->addSql('DROP TABLE stores');
        $this->addSql('DROP TABLE stores_elements_stocks');
    }
}
