#!/usr/bin/env node

// Explicitly synchronize non-secret Kubernetes configuration with project
// sources. This command only writes a deterministic manifest.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { buildResources, loadConfiguration } from './lib/k8s-config-resources.mjs';
import { loadK8sSettings } from './lib/k8s-settings.mjs';

function parseArguments() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');
  if (args.length !== Number(checkOnly)) {
    throw new Error('Usage: npm run k8s:config:sync [-- --check]');
  }
  return checkOnly;
}

function scalar(value) {
  return JSON.stringify(String(value));
}

function renderResource(resource) {
  const lines = [
    'apiVersion: v1',
    'kind: ConfigMap',
    'metadata:',
    `  name: ${scalar(resource.metadata.name)}`,
    `  namespace: ${scalar(resource.metadata.namespace)}`,
    ...(resource.immutable ? ['immutable: true'] : []),
    'data:',
  ];
  for (const [key, value] of Object.entries(resource.data)) {
    const text = String(value);
    if (text.includes('\n')) {
      lines.push(`  ${scalar(key)}: ${text.endsWith('\n') ? '|' : '|-'}`);
      for (const line of text.replace(/\n$/, '').split('\n')) {
        lines.push(`    ${line}`);
      }
    } else {
      lines.push(`  ${scalar(key)}: ${scalar(text)}`);
    }
  }
  return lines.join('\n');
}

try {
  const checkOnly = parseArguments();
  const { namespace, imageProfile } = loadK8sSettings();
  const config = loadConfiguration(imageProfile);

  const resources = buildResources(config, namespace);
  const output = `# Generated by npm run k8s:config:sync; edit sources and synchronize again.\n${resources.map(renderResource).join('\n---\n')}\n`;
  const path = join('kubernetes', 'generated', namespace, 'configmaps.yaml');

  if (checkOnly) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== output) {
      throw new Error(`Kubernetes ConfigMaps are out of sync: ${path}`);
    }
    console.log(`Kubernetes ConfigMaps are in sync: ${path}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    if (!existsSync(path) || readFileSync(path, 'utf8') !== output) {
      writeFileSync(path, output);
    }
    console.log(`Generated ${path}`);
  }
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
