#!/usr/bin/env node

// Synchronize computed non-secret Helm values with project configuration.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { buildGeneratedValues, loadConfiguration } from './lib/k8s-config-resources.mjs';
import { loadK8sSettings } from './lib/k8s-settings.mjs';

function parseArguments() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');
  if (args.length !== Number(checkOnly)) {
    throw new Error('Usage: npm run k8s:config:sync [-- --check]');
  }
  return checkOnly;
}

function renderValues(values, depth = 0) {
  const lines = [];
  for (const [key, value] of Object.entries(values)) {
    const prefix = `${'  '.repeat(depth)}${key}:`;
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      lines.push(prefix, renderValues(value, depth + 1));
    } else {
      lines.push(`${prefix} ${JSON.stringify(String(value))}`);
    }
  }
  return lines.join('\n');
}

try {
  const checkOnly = parseArguments();
  const { namespace, imageProfile } = loadK8sSettings();
  const config = loadConfiguration(imageProfile);

  const output = `# Generated by npm run k8s:config:sync; edit sources and synchronize again.\n${renderValues(buildGeneratedValues(config))}\n`;
  const path = join('kubernetes', 'generated', namespace, 'generated-values.yaml');

  if (checkOnly) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== output) {
      throw new Error(`Helm values are out of sync: ${path}`);
    }
    console.log(`Helm values are in sync: ${path}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    if (!existsSync(path) || readFileSync(path, 'utf8') !== output) {
      writeFileSync(path, output);
    }
    console.log(`Generated ${path}`);
  }
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
