<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422170741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE news_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE news ADD status_id INT NOT NULL');
        $this->addSql('ALTER TABLE news ADD CONSTRAINT FK_1DD399506BF700BD FOREIGN KEY (status_id) REFERENCES news_status (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_1DD399506BF700BD ON news (status_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE news_status');
        $this->addSql('ALTER TABLE news DROP CONSTRAINT FK_1DD399506BF700BD');
        $this->addSql('DROP INDEX IDX_1DD399506BF700BD');
        $this->addSql('ALTER TABLE news DROP status_id');
    }
}
